/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import Foundation
import GRDB

// MARK: - The destination address the wire already gave us

/// One member's destination address, exactly as the server itself named it in
/// its answer to the move THIS operation issued.
///
/// THE ADDRESS PROBLEM, closed where it is created. A `PendingOperation` names
/// its members by their address in the SOURCE folder, and on IMAP an address is
/// `(folder, UID, UIDVALIDITY)`. **A move changes that address**, and the server
/// hands us the new one in `COPYUID` — which `IMAPProvider.copyProvenSourceUIDs`
/// reads only to VALIDATE and then discards. This type is that discarded half,
/// carried to the drain so the move can be finished LOCALLY instead of being
/// repaired later by sync on weaker (RFC 822) evidence.
///
/// 🚨 **PROVIDER-NEUTRAL, because the discard was never IMAP-specific.** The
/// identical sentence is true of Microsoft Graph: `POST /messages/{id}/move`
/// answers with the moved message **carrying its new `id`**, Graph ids churn on
/// every folder move by default (no `Prefer: IdType="ImmutableId"` is sent
/// anywhere in this app), and `ExchangeProvider.moveMessage` bound that response
/// to `_`. The two address spaces differ only in what an address IS — a UID
/// inside an epoch on IMAP, an opaque resource id with NO epoch space on Graph —
/// so the id is a `String` and the epoch is OPTIONAL. `KNOWN_ISSUES.md`
/// `IOS-GRAPH-002`, `MIS-IOS-003` instance 5, `MIS-006` instance 5.
///
/// ⚠ NOT an rfc822 Message-ID, and never derived from one. ADR-IOS-068 / D4
/// forbids the Message-ID as mutation authority and forbids a `SEARCH` result
/// from ever being a mutation target. The authority here is the wire's own
/// answer to the move THIS operation issued — attempt-correlated by
/// construction, and strictly stronger than any identity probe.
struct ProvenDestinationAddress: Sendable, Equatable {
    /// The provider id the operation named — the SOURCE UID as a string on
    /// IMAP, the source Graph resource id on Exchange.
    let sourceProviderId: String
    /// The provider id the server assigned to the copy it created in the
    /// destination — the destination UID as a string on IMAP, the `id` of the
    /// message resource Graph returned from `/move` on Exchange.
    let destinationProviderId: String
    /// The destination address space's epoch, when the provider HAS one: the
    /// destination mailbox's UIDVALIDITY, stamped on the same `COPYUID`.
    ///
    /// **`nil` means the provider has no epoch space at all** (Graph), NOT that
    /// an epoch was expected and went missing — `IMAPProvider.move` refuses
    /// before any wire mutation when a destination epoch is unreadable, so it
    /// never reaches this type unset. `finishMove`'s G2 leaves the row's stamp
    /// unread for a `nil` epoch, which is both the correct value and the safe
    /// one (see G2).
    let destinationUidValidity: UInt32?
}

/// What one provider move attempt DISPOSITIONED, and where the server said the
/// copies landed.
///
/// Top-level rather than nested in `IMAPProvider` because it has TWO producers:
/// `IMAPProvider.move(ids:from:to:admittedUidValidity:)` and
/// `ExchangeProvider.moveProvingDestinations(ids:from:to:)`. Both feed the same
/// consumer — `AccountManager.executeOperation`'s `.move` case — so one
/// type keeps the two arms from drifting.
struct MoveOutcome: Sendable {
    /// The subset of the requested ids this attempt DISPOSITIONED (per-member
    /// retirement, B-2).
    let provenIds: [String]
    /// Per-member destination addresses the server itself named. Never a
    /// superset of `provenIds`; frequently empty.
    let provenDestinations: [ProvenDestinationAddress]
}

/// One applied re-key. The local row that used to live at `oldHeaderId` now
/// lives at `newHeaderId` and carries `newProviderMessageId`.
///
/// Consumed OUTSIDE the GRDB write by the THREE stores that key by
/// `messageHeader.id` but do not live in that database — all of them through
/// the one mirror point, `AccountManager.publishRekeys`: the FTS index
/// (`SearchIndex.rekeyHeaders`, a separate SQLite pool), the in-memory undo
/// stack (`UndoService.applyRekeys`), and the body-asset manifest
/// (`BodyAssetStore.rekeyContentKey`, a third SQLite pool in the App Group
/// container).
///
/// ⚠ THIS SAID "the two stores" UNTIL R13-U8, AND R12-T7 IS WHAT FALSIFIED IT
/// — the commit that added the third mirror did not come back and change the
/// count here. That is the class, not the instance: a tally in prose has no
/// compiler and no test behind it, so it is correct only until the next
/// consumer appears. The number is REGENERATED by the callers of this type
/// (`rg 'HeaderRekeyRecord|applyRekeys|rekeyHeaders|rekeyContentKey'` over
/// `TabMail/ Shared/`), never read off this sentence — re-run it before
/// restating the count, and add the new store to `publishRekeys` rather than
/// to a second mirror point.
struct HeaderRekeyRecord: Sendable, Equatable {
    let oldHeaderId: String
    let newHeaderId: String
    let newProviderMessageId: String
}

// MARK: - The re-key itself

enum MessageHeaderRekey {

    /// Re-key ONE local header row to a new primary key, carrying every child
    /// row the delete would otherwise destroy.
    ///
    /// **EXTRACTED, NOT INVENTED.** This is the sequence
    /// `SyncEngine.runSyncMessages` has always run for a UID remap (the block
    /// that logs `[Sync] UID remap:`), lifted here so the drain can run the
    /// IDENTICAL re-key EARLIER, authorized by the server's own `COPYUID`
    /// rather than by an RFC 822 match. Both callers share this body, so the
    /// two paths cannot drift.
    ///
    /// **ORDERING IS LOAD-BEARING.** The body fetch, the user-label capture and
    /// BOTH deletes must precede EVERY exit — including the collision return —
    /// or the leg that skips the re-insert still leaves the orphan behind. The
    /// `messageBody` FK cascade that used to reclaim the body row is gone as of
    /// Stage D, so the delete is explicit.
    ///
    /// **THE TWO CHILD TABLES THAT CASCADE**, both declared
    /// `.references("messageHeader", onDelete: .cascade)` in `AppDatabase`, and
    /// both silently destroyed by the delete unless handled here:
    ///  - `messageReference` (threading references) is **REBUILT** from the
    ///    migrated header's own `References` / `In-Reply-To` content, so the
    ///    rebuild is exact — the header carries its own source of truth.
    ///  - `messageUserLabel` (user-assigned labels) has **NO rebuild source**;
    ///    nothing else in the database knows which labels the user applied. It
    ///    is therefore **CAPTURED before the delete and re-inserted under the
    ///    new id**, the same shape as the body. Losing it is silent loss of
    ///    user state, which is why this one is carry-forward and not rebuild.
    ///
    /// **NOT FK-BOUND TO `messageHeader`, so the delete above does not touch
    /// them.** This list used to read *"`bodyAsset`, `pendingRender`,
    /// `chatIdMapping` … each is swept by its own headerId-prefix maintenance
    /// path"*, and by R13-U8 only the third of those three was still true:
    ///  - **`bodyAsset` is NO LONGER out of scope.** R12-T7: once the drain
    ///    began finishing moves locally, `BodyAssetMaintenance.pruneOrphans`
    ///    reclassified a live message's cached bodies and attachments as
    ///    orphans and DELETED them, because its only recovery leg
    ///    (`MessageContentStore.recoverMovedContentKey`) matches an UNCHANGED
    ///    `providerMessageId` — and a re-key is exactly the shape that changes
    ///    it. It is now mirrored outside this write by
    ///    `AccountManager.publishRekeys` → `BodyAssetStore.rekeyContentKey`.
    ///    ⚠ A caller of `apply` that does not route through `publishRekeys`
    ///    still owes that mirror; this function cannot do it (different pool,
    ///    and it must not run inside the GRDB write).
    ///
    ///    🚨 **AND SOME IN-TREE CALLERS DO NOT MEET IT — stated as the negative
    ///    case, because the sentence above stated an obligation and left a
    ///    reader to assume it was met (`MIS-019`: an absolute like "all other
    ///    callers route through `publishRekeys`" is exactly the shape that
    ///    produced this gap).** They are NAMED rather than counted, so the
    ///    sentence cannot go stale as an integer (`MIS-007`). ⚠ Re-derive the
    ///    roster with an instrument this doc block cannot itself enter — a bare
    ///    `rg 'MessageHeaderRekey.apply'` matches the bullets below and counts
    ///    its own recording (`MIS-033`; `IOS-DOC-002` requires the predicate):
    ///    ```
    ///    rg -n --pcre2 '^(?!\s*(///|//)).*MessageHeaderRekey\.apply\(' \
    ///       TabMail/ Shared/ TabMailNotificationService/
    ///    ```
    ///    → 5 at R17-1 (was 3), and **still 5 at R18-D5**. Check each hit
    ///    against `AccountManager.publishRekeys`; the ones that do NOT
    ///    reach it are:
    ///     * the **UID-remap block in `SyncEngineFullSync`** — the
    ///       `guard try MessageHeaderRekey.apply(…)` inside the stale-message
    ///       loop;
    ///     * **`SyncEngine.canonicalizeLocalRows`** — the `willRekey`
    ///       leg, which became a caller in R17-1 (it hand-rolled the identical
    ///       delete+reinsert before that, destroying both children outright, so
    ///       adopting this carrier strictly reduced its loss);
    ///     * **`DemoProvider.move`**, also R17-1 — demo mode only, and demo has
    ///       no `publishRekeys` path at all;
    ///     * 🚨 **`DraftStore.migrateExactPlaceholder` — ADDED R18-D5. The
    ///       roster said THREE and the predicate returns FIVE, and the arithmetic
    ///       is the whole point: this bullet list is the "does not reach
    ///       `publishRekeys` AND still owes a leg" set, so it is NOT simply
    ///       `5 − 2`.** `BackfillBodyQueue.rekeyRemappedHeader` also never
    ///       reaches `publishRekeys` and is correctly absent, because it
    ///       DISCHARGES BOTH MIRRORS INLINE — `SearchIndex.rekeyHeaders` and
    ///       `BodyAssetStore.rekeyContentKey` / `deleteAllAssets` on the
    ///       `.migrated` / `.duplicateDropped` split. `migrateExactPlaceholder`
    ///       discharges only the FTS leg (its caller runs
    ///       `SearchIndex.rekeyHeaders` on the `rekeyed == true` branch, and
    ///       `MessageContentStore.releaseUnowned(stores: [.searchIndex, .body])`
    ///       on the false branch), and does NOT call `rekeyContentKey`. ⚠ The
    ///       false completeness claim being corrected is `f8a437125`'s commit
    ///       body, which said it was "naming all three".
    ///       **`bodyAsset` leg — NOT discharged, and the population it would
    ///       carry is provably EMPTY, which is why this is a doc correction and
    ///       not a fix.** Verified rather than assumed, by censusing the
    ///       manifest's row-CREATING entry points (`prepare`/`publish` have no
    ///       callers outside `BodyAssetStore.write`, so the class is exactly
    ///       `writeInlineImage` / `writeAttachment` / `makeInlineImageWriter`):
    ///       ```
    ///       rg -n 'BodyAssetStore\.(writeInlineImage|writeAttachment|prepare|publish|makeInlineImageWriter)\(' \
    ///          TabMail/ Shared/ TabMailNotificationService/
    ///       ```
    ///       → 5 non-comment sites at R18-D5: `GmailAPI`, `GraphAPI`,
    ///       `IMAPFetchMapping`, `BodyFetchProcessor` (all four take their
    ///       content key from a header being fetched FROM the provider) and
    ///       `AttachmentListView` (reached only AFTER
    ///       `manager.fetchAttachment(for:section:)` returns bytes). A draft
    ///       placeholder's `messageId` is
    ///       `PendingOperation.draftPlaceholderMessageId` — `draft-<draftId>…`,
    ///       not an address any provider can fetch — so none of the five can
    ///       ever produce a row under a placeholder content key. Independently:
    ///       `AccountManagerActions` creates the placeholder header and its
    ///       `MessageBody` in the SAME write, with
    ///       `MessageBody.plainTextToHTML(draft.body)` — no `cid:` inline images
    ///       and no attachment sections — so there is nothing for a render path
    ///       to write even if one ran.
    ///       **`UndoService` leg** — inherits the same disposition as the two
    ///       `SyncEngineFullSync` callers below: an undo entry naming the old id
    ///       resolves nothing and fails closed, bounded by the undo stack's
    ///       lifetime.
    ///       ⚠ **What would falsify this and make it a real loss path:** a draft
    ///       placeholder gaining attachment sections or `cid:` inline images in
    ///       its locally-composed body, or any new `BodyAssetStore` write site
    ///       keyed by a header id that was not fetched from a provider. Re-run
    ///       the predicate above before assuming the population is still empty.
    ///    Leg by leg, for the two `SyncEngineFullSync` callers:
    ///     * **FTS — DISCHARGED, by the caller itself, not by `publishRekeys`.**
    ///       The UID-remap block appends to `ftsRekeys` directly; the
    ///       canonicalizer returns its pair in the `ftsRekey` tuple, which
    ///       `runSyncMessages` folds into the same `ftsRekeys`. Both end at the
    ///       same `SearchIndex.rekeyHeaders`, and both deliberately keep the
    ///       re-keyed old id OFF the `staleIds` channel (`uidMigratedSet` is
    ///       filtered out of `staleFiltered`) because the FTS entry must MOVE,
    ///       not be removed. So the obligation is not "all three legs" for every
    ///       caller — assuming that is how a reader concludes the sync path is
    ///       broken in a way it is not. `DemoProvider.move` has no FTS mirror at
    ///       all, which is a demo-only cost and is not this function's to close.
    ///     * **`UndoService.applyRekeys` — NOT discharged.** An undo entry that
    ///       names the old header id keeps naming it, so the undo resolves
    ///       nothing and fails closed. Bounded by the undo stack's lifetime.
    ///     * **`BodyAssetStore.rekeyContentKey` — NOT discharged, and the
    ///       consequence is not merely a cache miss.** The old key's assets
    ///       become orphans while the carried-forward `messageBody` row at the
    ///       NEW key still references them through `tabmail-asset://` — the
    ///       R12-T7 mechanism `publishRekeys` calls *"A REGRESSION, NOT MERELY
    ///       AN EDGE"*. The old id rides neither the re-key channel nor the
    ///       `staleIds` removal (which does clear `stores: [.searchIndex, .body]`).
    ///
    ///    **Why it is accepted under THE MANTRA rather than fixed, and the
    ///    load-bearing half re-verified at `07a4bb703` rather than inherited.**
    ///    `git show 07a4bb703:` that file: the UID-remap block already did
    ///    collision-skip → `migrated.insert(db)` → `body.id = newId;
    ///    body.insert(db)`, already fed `ftsRekeys`, and already kept the
    ///    re-keyed id off `staleIds` — this `apply` is that sequence extracted
    ///    verbatim. And `git ls-tree 07a4bb703` shows `BodyAssetStore` and
    ///    `BodyAssetMaintenance.pruneOrphans` present while `publishRekeys`,
    ///    `UndoService.applyRekeys` and `BodyAssetStore.rekeyContentKey` are
    ///    **absent entirely**. So the sync path's exposure is byte-identical to
    ///    shipped: v3 built the mirror for the DRAIN, whose re-key was a v3
    ///    regression against an ordinary primary path, and did not extend it to
    ///    a path v3 never changed. It self-heals at
    ///    `SyncConfig.bodyCacheTTLHours`, so the recoverability test says fail
    ///    closed and let it be. Registered, not mechanised.
    ///  - **`pendingRender` is a DEAD TABLE.** `v32` created it for durable
    ///    body staging; nothing has INSERTed, SELECTed or UPDATEd it since. The
    ///    only surviving statements are two DELETEs — `SettingsView`'s reset
    ///    list and `AccountManagerUidValidityReset`'s step (iv). It has no rows
    ///    to orphan and no headerId-prefix sweep of its own, so naming it here
    ///    described a hazard that does not exist. ⚠ The retention REASON given
    ///    here was wrong and is corrected: *"a registered migration is
    ///    immutable"* freezes `v32`'s NAME and BODY (Data Integrity rule 5), and
    ///    says nothing about whether a NEW `v84` may `DROP TABLE pendingRender`
    ///    — it may. The actual reason is the launch path: a drop can only be
    ///    reached through a registered migration, the blocking chain was just
    ///    cut 27,601 ms → ~3,241 ms by moving work OFF it, and dropping a table
    ///    that is provably empty in every database reclaims nothing. The two
    ///    surviving DELETEs are kept for a second, independent reason — both
    ///    are members of safety ENUMERATIONS, so removing them is fail-dangerous
    ///    if body staging is ever revived. Adjudicated in `KNOWN_ISSUES.md`
    ///    `IOS-MIGRATION-005`; the conclusion (do not "clean it up" with a DROP)
    ///    is unchanged.
    ///  - **`chatIdMapping`** is the one the original sentence still fits:
    ///    swept by `ChatIdTranslator.purgeMappingsForFolder`, which matches
    ///    `realId` with `MessageIdentity.headerIdBelongsToFolder`. Pre-existing
    ///    and unchanged by this helper — sync's UID-remap path has re-keyed
    ///    headers out from under it since long before the drain did.
    ///
    /// - Returns: `true` when `migrated` was inserted. `false` when a row
    ///   already occupies the new id — in which case the old row is still gone,
    ///   which is the pre-existing behaviour of the sync path's `continue`
    ///   (the new id is the survivor and the old id's FTS entry is dropped by
    ///   the caller's ordinary stale handling rather than re-keyed).
    @discardableResult
    static func apply(from old: MessageHeader, to migrated: MessageHeader, db: Database) throws -> Bool {
        let oldId = old.id
        let newId = migrated.id
        // Everything the delete destroys is read FIRST — see "ORDERING IS
        // LOAD-BEARING" above. Both deletes then run unconditionally, so the
        // collision return below cannot leave a duplicate plus a leak.
        let oldBody = try MessageBody.fetchOne(db, key: ContentKey(rawValue: oldId))
        let carriedLabels = try MessageUserLabel
            .filter(Column("messageId") == oldId)
            .fetchAll(db)
        try old.delete(db)
        _ = try MessageBody.deleteOne(db, key: ContentKey(rawValue: oldId))
        // Defensive — if a concurrent path already inserted this id, skip
        // instead of throwing UNIQUE.
        guard try MessageHeader.fetchOne(db, key: newId) == nil else { return false }
        try migrated.insert(db)
        if var body = oldBody {
            body.id = ContentKey(rawValue: newId)
            try body.insert(db)
        }
        for label in carriedLabels {
            var carried = label
            carried.messageId = newId
            try carried.insert(db)
        }
        try ThreadUtils.insertMessageReferences(for: migrated, db: db)
        return true
    }

    /// FINISH THE MOVE LOCALLY: re-key each member this attempt's `COPYUID`
    /// named, from its source address to the destination address the server
    /// itself assigned.
    ///
    /// Called from inside the SAME write transaction that deletes the completed
    /// `PendingOperation`, so the crash window is no worse than today's: either
    /// the op is retired and the rows are re-keyed, or neither happened and the
    /// op re-executes (idempotently).
    ///
    /// WHY THIS EXISTS. `AccountManager.optimisticMoveToFolder` moves the
    /// row's `folderId`/`folderPath` to the destination, NILS
    /// `observedUidValidity`, and leaves the primary key and `messageId` at
    /// their SOURCE values. Until something repairs that, the row is refused by
    /// `admittedOrdinaryActionTargets` (which requires a live epoch and a
    /// parseable UID), so **the user's next gesture on a just-moved message is
    /// a silent dead no-op** — swipe-archive, then swipe-delete from Archive,
    /// and nothing happens at all. Sync's UID-remap path repairs it eventually,
    /// but only if the remnant is selected as stale (which compares a SOURCE UID
    /// against the DESTINATION folder's UID floor — two different address
    /// spaces) AND its rfc822 Message-ID matches a new remote message. Either
    /// can fail permanently.
    ///
    /// **THE FOUR GUARDS**, each closing a specific hazard:
    ///
    /// **G1 — pairing** is enforced upstream in
    /// `IMAPProvider.copyProvenDestinations`, because it is a property of the
    /// whole `COPYUID` response rather than of one member.
    ///
    /// **G2 — the epoch stamp is the MIRROR-IMAGE guard.** The stamp is written
    /// only when the epoch the server reported EQUALS the destination
    /// `Folder.lastKnownUidValidity`; otherwise the row is re-keyed and the
    /// stamp is left NIL. `Folder.lastKnownUidValidity` is written only by sync
    /// paths, so a drain-time stamp can leave the row FRESHER than the folder
    /// row — and `AccountManager.roleMoveRejectDispositions` treats a
    /// POSITIVE disagreement (`observed != nil && observed != liveEpoch`) as
    /// `.terminalStale`, its ONLY terminal arm. Stamping optimistically would
    /// therefore TERMINALLY DROP the user's next gesture: the exact inverse of
    /// the bug this function fixes. A nil stamp is `.retainedForRetry`, which is
    /// recoverable by the next sync of that folder.
    ///
    /// **A provider with NO epoch space takes the same nil arm, and for the same
    /// reason.** Graph has no UIDVALIDITY, so `destinationUidValidity` is `nil`
    /// and the stamp is left unread. That is not a degraded case: an invented
    /// stamp on an Exchange row would be a *positive* disagreement with the
    /// folder's own `nil`, i.e. the terminal arm again. Nil is both the true
    /// value and the safe one.
    ///
    /// **G3 — collision and TOCTOU.** The row must still be the one THIS
    /// operation moved (same account, same provider id, still sitting in this
    /// op's destination folder); a vanished or already-repaired row is a
    /// no-op, and a new id that is already occupied is skipped by
    /// `apply(from:to:db:)`. GRDB's single writer serializes this against a
    /// concurrent sync, so this is an ordering concern, never corruption.
    ///
    /// **G4 — unchanged behaviour when `COPYUID` does not name the member.**
    /// The decision is PER MEMBER, never per operation: a batch can be partly
    /// addressable, and an unnamed member simply keeps today's behaviour (the
    /// remnant survives until sync repairs it).
    ///
    /// - Parameter onCollidedRekey: called with the OLD header id of each member
    ///   whose re-key hit the collision return of `apply(from:to:db:)` — the old
    ///   row is gone and nothing was re-keyed to take its place. A caller that
    ///   mirrors this table into a store keyed by `messageHeader.id` MUST drop
    ///   that id there, or the store keeps an entry with no header behind it
    ///   (the *indexed but unfindable* class). The sync path already does this
    ///   via its own `staleIds` disposition; the drain does it through this
    ///   channel, so both callers converge on one outcome. Defaulted because it
    ///   is auxiliary: a caller that keeps no store outside this database has
    ///   nothing to compensate, and the applied records alone describe it.
    /// - Returns: the re-keys actually applied, for the callers that must
    ///   mirror them into stores outside this database.
    static func finishMove(
        _ op: PendingOperation,
        destinations: [ProvenDestinationAddress],
        db: Database,
        onCollidedRekey: (String) -> Void = { _ in }
    ) throws -> [HeaderRekeyRecord] {
        guard op.type == .move, !destinations.isEmpty,
              let destinationPath = op.destinationPath,
              destinationPath != op.folderPath
        else { return [] }

        let destinationFolderId = MessageIdentity.folderId(
            accountId: op.accountId, folderPath: destinationPath)
        // G2 — read the folder's OWN epoch; the stamp is admitted only if the
        // server's reported epoch agrees with it.
        let folderEpoch = try Folder.fetchOne(db, key: destinationFolderId)?.lastKnownUidValidity
        let memberIds = Set(op.messageIds)

        var applied: [HeaderRekeyRecord] = []
        for destination in destinations {
            // G4 — a destination this operation never named is not this
            // operation's business.
            guard memberIds.contains(destination.sourceProviderId) else { continue }
            let oldId = MessageIdentity.headerId(
                accountId: op.accountId, folderPath: op.folderPath,
                messageId: destination.sourceProviderId)
            let newMessageId = destination.destinationProviderId
            let newId = MessageIdentity.headerId(
                accountId: op.accountId, folderPath: destinationPath,
                messageId: newMessageId)
            guard newId != oldId else { continue }
            // G3 — only the exact row this operation optimistically moved. A
            // row that vanished, that a sync already canonicalized, or that a
            // later gesture moved elsewhere is left alone.
            guard let row = try MessageHeader.fetchOne(db, key: oldId),
                  row.accountId == op.accountId,
                  row.messageId == destination.sourceProviderId,
                  row.folderPath == destinationPath,
                  row.folderId == destinationFolderId
            else { continue }

            var migrated = row
            migrated.id = newId
            migrated.messageId = newMessageId
            // G2 — see the discussion above. Fresher-than-the-folder is worse
            // than unknown, because only the former is terminal. A provider
            // with no epoch space reports `nil` and takes the same arm.
            if let provenEpoch = destination.destinationUidValidity,
               folderEpoch == Int(provenEpoch) {
                migrated.observedUidValidity = Int(provenEpoch)
            } else {
                migrated.observedUidValidity = nil
            }

            guard try apply(from: row, to: migrated, db: db) else {
                // The new id was already occupied, so `apply` deleted the old
                // row and inserted nothing. `oldId` now names no header at all
                // — report it so the caller can drop it from the stores that
                // key by header id and live outside this database.
                onCollidedRekey(oldId)
                continue
            }
            applied.append(HeaderRekeyRecord(
                oldHeaderId: oldId, newHeaderId: newId,
                newProviderMessageId: newMessageId))
        }
        return applied
    }
}
