/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import Testing
import Foundation
import SwiftMail
@testable import TabMail
#if canImport(Darwin)
import Darwin
#endif

/// T0.2 — the red-first proof for the two `FakeIMAPServer` mechanisms the v3
/// safety work is built on. Both mechanisms landed with T0.1 (they are woven
/// through the fake's state and every mutating handler, so they could not be
/// excluded); what did NOT land is the evidence that they actually work.
///
/// **Deliverable 1 — the wrong-message wire oracle.** Every mutating IMAP
/// command (`UID STORE`, `UID MOVE`, `UID COPY`, `UID EXPUNGE`, plain
/// `EXPUNGE`) resolves its target UID to the mailbox's CURRENT occupant
/// in-lock, pre-mutation, and records a `WrongMessageViolation` when that
/// occupant's Message-ID is not one the test declared it was mutating. This is
/// the primary instrument for C3-I1…C3-I6 (`PLAN_IOS_REFACTOR_V3.md` §3.2):
/// every later Tier-2/Tier-3 test asserts `wrongMessageViolations().isEmpty`,
/// and an assertion that can never fail proves nothing. These tests are the
/// positive control for that assertion.
///
/// **Deliverable 2 — the epoch-replacement model.**
/// `resetMailboxAfterNextSuccessfulResponse` applies a complete mailbox epoch
/// replacement (UIDVALIDITY + message list + flags) immediately after the
/// matching command's successful response is written to the client. That is
/// what makes the mid-sequence epoch hazard reproducible at all: a UID
/// resolved under epoch E1 and mutated after the mailbox has moved to E2
/// lands on a different message. A later Tier-3 item uses exactly this to
/// prove the IMAP move path cannot mutate the wrong message.
///
/// **Why these drive the wire directly instead of a provider API.** These are
/// harness tests: they pin the FAKE's contract, so they must stay true no
/// matter how production changes. A test that produced the mis-target by
/// exploiting a production defect would go green the moment that defect is
/// fixed — an oracle proof that self-destructs. Here the mis-target comes from
/// the TEST's own declaration (it registers B and mutates A's UID), which no
/// production change can ever make correct. One test
/// (`oracleObservesProductionIMAPProviderStore`) closes the loop by proving
/// the oracle also sees traffic generated by the real `IMAPProvider`.
///
/// `.serialized` — the fake binds a listening socket; parallel tests would
/// contend on ephemeral port allocation.
@Suite("FakeIMAPServer wrong-message oracle + epoch-replacement model", .serialized)
struct FakeIMAPServerOracleTests {

    // MARK: - Fixtures

    private static func rfc822(messageId: String, subject: String = "oracle-fixture") -> String {
        """
        From: Test Sender <sender@example.com>\r
        To: Recipient <recipient@example.com>\r
        Subject: \(subject)\r
        Date: Thu, 01 Jan 2026 00:00:00 +0000\r
        Message-ID: <\(messageId)>\r
        Content-Type: text/plain; charset=utf-8\r
        \r
        oracle fixture body.\r

        """
    }

    private static func message(uid: Int, id: String) -> FakeIMAPServer.Message {
        FakeIMAPServer.makeMessage(uid: uid, rfc822Text: rfc822(messageId: id))
    }

    /// Runs `body` against a freshly logged-in raw SwiftMail client and logs
    /// out before returning. Driving the wire directly is deliberate — see the
    /// suite doc comment. The logout is awaited rather than deferred into a
    /// detached `Task`, so it can never race the fake's socket teardown.
    private static func withClient<T>(
        _ server: FakeIMAPServer,
        _ body: (SwiftMail.IMAPServer) async throws -> T
    ) async throws -> T {
        let client = SwiftMail.IMAPServer(host: "127.0.0.1", port: server.port, useTLS: false)
        try await client.connect()
        try await client.login(username: server.username, password: server.password)
        do {
            let result = try await body(client)
            try? await client.logout()
            return result
        } catch {
            try? await client.logout()
            throw error
        }
    }

    // MARK: - Deliverable 1: the oracle fires

    /// THE headline red-first proof for T0.2: a `UID STORE` aimed at a UID
    /// whose current occupant is not the message the test declared it was
    /// mutating raises exactly one `WrongMessageViolation`, naming the
    /// command, the mailbox, the UID, and the Message-ID that was actually
    /// hit.
    ///
    /// Inversion evidence (recorded 2026-07-30): with `recordOracleCheck`'s
    /// body neutralized to an immediate `return`, this test fails at the
    /// `violations.count == 1` expectation — it goes green-when-it-should-be-
    /// red. It passes only because the oracle exists.
    @Test("oracle fires on a UID STORE aimed at a UID the test never declared")
    func oracleFiresOnMisTargetedUIDStore() async throws {
        let occupantId = "oracle-store-occupant@example.com"
        let declaredId = "oracle-store-declared@example.com"
        let occupantUID = 101
        let declaredUID = 102
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: declaredUID, id: declaredId),
            ],
        ])
        // The test declares it is mutating `declaredId` — and then deliberately
        // mis-targets UID 101, whose current occupant is `occupantId`.
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.store(flags: [.seen], on: UIDSet(UID(occupantUID)), operation: .add)
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command.hasPrefix("UID STORE"))
        #expect(violations[0].mailbox == "INBOX")
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        #expect(violations[0].expectedRfcs == [declaredId])
        // The oracle OBSERVES; it never blocks. The wrong-message mutation
        // really did land — which is precisely the class of defect it exists
        // to make visible.
        #expect(server.flags(in: "INBOX", uid: occupantUID).contains("\\Seen"))
    }

    /// The negative control for the test above: the same STORE, aimed at the
    /// UID the test DID declare, records nothing. Without this, a
    /// permanently-firing oracle would also satisfy the positive proof.
    @Test("oracle stays silent on a correctly targeted UID STORE")
    func oracleStaysSilentOnCorrectlyTargetedUIDStore() async throws {
        let declaredId = "oracle-store-correct@example.com"
        let declaredUID = 103
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [Self.message(uid: declaredUID, id: declaredId)],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.store(flags: [.seen], on: UIDSet(UID(declaredUID)), operation: .add)
        }

        #expect(server.wrongMessageViolations().isEmpty)
        #expect(server.flags(in: "INBOX", uid: declaredUID).contains("\\Seen"))
    }

    /// The oracle is OPT-IN. While no expectation has ever been registered,
    /// every mutating handler's check is a single `isEmpty` branch — this is
    /// what keeps the other ~7,700 tests behaviorally unchanged. Exercises the
    /// whole mutating surface with no registration at all.
    @Test("oracle is inert until a test registers an expectation")
    func oracleIsInertWhenNoExpectationRegistered() async throws {
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: 111, id: "oracle-inert-a@example.com"),
                Self.message(uid: 112, id: "oracle-inert-b@example.com"),
                Self.message(uid: 113, id: "oracle-inert-c@example.com"),
                Self.message(uid: 114, id: "oracle-inert-d@example.com"),
            ],
            "Archive": [],
        ])
        server.setFlags(["\\Deleted"], in: "INBOX", uid: 114)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.store(flags: [.flagged], on: UIDSet(UID(111)), operation: .add)
            try await client.copy(messages: UIDSet(UID(111)), to: "Archive")
            try await client.move(messages: UIDSet(UID(112)), to: "Archive")
            try await client.expunge(messages: UIDSet(UID(113)))
            try await client.expunge()
        }

        // Every mutating command ran, and the oracle recorded nothing.
        let commands = server.recordedCommands()
        #expect(commands.contains { $0.hasPrefix("UID STORE") })
        #expect(commands.contains { $0.hasPrefix("UID COPY") })
        #expect(commands.contains { $0.hasPrefix("UID MOVE") })
        #expect(commands.contains { $0.hasPrefix("UID EXPUNGE") })
        #expect(commands.contains("EXPUNGE"))
        #expect(server.wrongMessageViolations().isEmpty)
    }

    @Test("oracle fires on a mis-targeted UID MOVE")
    func oracleFiresOnMisTargetedUIDMove() async throws {
        let occupantId = "oracle-move-occupant@example.com"
        let declaredId = "oracle-move-declared@example.com"
        let occupantUID = 121
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: 122, id: declaredId),
            ],
            "Archive": [],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            // Default capabilities advertise MOVE + UIDPLUS, so SwiftMail
            // issues an atomic `UID MOVE` rather than the COPY/STORE/EXPUNGE
            // fallback.
            try await client.move(messages: UIDSet(UID(occupantUID)), to: "Archive")
        }

        #expect(server.recordedCommands().contains { $0.hasPrefix("UID MOVE") })
        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command == "UID MOVE")
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        #expect(server.messageIDs(in: "Archive") == ["<\(occupantId)>"])
    }

    @Test("oracle fires on a mis-targeted UID COPY")
    func oracleFiresOnMisTargetedUIDCopy() async throws {
        let occupantId = "oracle-copy-occupant@example.com"
        let declaredId = "oracle-copy-declared@example.com"
        let occupantUID = 131
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: 132, id: declaredId),
            ],
            "Archive": [],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.copy(messages: UIDSet(UID(occupantUID)), to: "Archive")
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command == "UID COPY")
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        // COPY leaves the source in place (RFC 3501 §6.4.7) — the wrong
        // message was duplicated, not moved.
        #expect(server.messageIDs(in: "INBOX").contains("<\(occupantId)>"))
        #expect(server.messageIDs(in: "Archive") == ["<\(occupantId)>"])
    }

    @Test("oracle fires on a mis-targeted UID EXPUNGE")
    func oracleFiresOnMisTargetedUIDExpunge() async throws {
        let occupantId = "oracle-uidexpunge-occupant@example.com"
        let declaredId = "oracle-uidexpunge-declared@example.com"
        let occupantUID = 141
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: 142, id: declaredId),
            ],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.expunge(messages: UIDSet(UID(occupantUID)))
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command == "UID EXPUNGE")
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        #expect(server.messageIDs(in: "INBOX") == ["<\(declaredId)>"])
    }

    /// Plain `EXPUNGE` is mailbox-WIDE (RFC 3501 §6.4.3) — it names no UID at
    /// all, so it is the one mutating command whose blast radius the caller
    /// cannot see. C3-I5 forbids it on every action path for exactly this
    /// reason; the oracle resolves the \Deleted set the server is about to
    /// destroy and reports every member the test never declared.
    @Test("oracle fires on a plain EXPUNGE that destroys an undeclared Deleted message")
    func oracleFiresOnMisTargetedPlainExpunge() async throws {
        let bystanderId = "oracle-expunge-bystander@example.com"
        let declaredId = "oracle-expunge-declared@example.com"
        let bystanderUID = 151
        let declaredUID = 152
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: bystanderUID, id: bystanderId),
                Self.message(uid: declaredUID, id: declaredId),
            ],
        ])
        // A pre-existing \Deleted bystander the test never gestured on, plus
        // the declared target — a mailbox-wide EXPUNGE takes both.
        server.setFlags(["\\Deleted"], in: "INBOX", uid: bystanderUID)
        server.setFlags(["\\Deleted"], in: "INBOX", uid: declaredUID)
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.expunge()
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command == "EXPUNGE")
        #expect(violations[0].uid == bystanderUID)
        #expect(violations[0].actualRfc == bystanderId)
        // Both really are gone — the declared one legitimately, the bystander
        // as collateral. Only the bystander is reported.
        #expect(server.messageIDs(in: "INBOX").isEmpty)
    }

    // MARK: - Deliverable 2: the epoch-replacement model

    /// `resetMailboxAfterNextSuccessfulResponse` models a UIDVALIDITY change
    /// taking effect at an await boundary — immediately after a successful
    /// protocol response, without pausing either side of the socket. This test
    /// proves all three properties the later Tier-3 move-path proof depends on:
    ///
    /// 1. **Not eager.** After arming, and after an unrelated command has come
    ///    and gone, a SELECT still reports the OLD epoch.
    /// 2. **UIDVALIDITY really changes at that point.** The first SELECT after
    ///    the armed command reports the NEW epoch.
    /// 3. **The UID's referent really changes.** UID 107 denoted message A
    ///    before the reset and a different message afterwards — demonstrated
    ///    by re-issuing the IDENTICAL `UID STORE 107` and watching it land on
    ///    the decoy while the oracle reports the wrong-message hit.
    ///
    /// Property 3 IS the mid-sequence epoch hazard, reproduced end-to-end at
    /// the wire: the two STOREs are byte-identical commands, one correct and
    /// one catastrophic, and only the epoch between them differs.
    ///
    /// Inversion evidence (recorded 2026-07-30), run in both directions
    /// because the two mechanisms must be shown to be separable:
    /// - With `recordOracleCheck` neutralized, the epoch assertions (1 → 2)
    ///   and the decoy-flag assertion still hold — the epoch model is proven
    ///   independently of the oracle — while only the violation assertion
    ///   fails.
    /// - With the post-response reset application neutralized (the
    ///   `postResponseMailboxResets` block in the client loop made
    ///   unreachable), this test fails at the UIDVALIDITY assertion
    ///   (`1 == 2`), at the occupant assertion (INBOX still holds the E1
    ///   target), and at the violation assertion — while every oracle test
    ///   above stays green.
    @Test("post-response reset changes UIDVALIDITY and repoints the UID at a different message")
    func postResponseResetChangesUidValidityAndUidOccupant() async throws {
        let targetId = "oracle-epoch-target@example.com"
        let decoyId = "oracle-epoch-decoy@example.com"
        let sharedUID = 107
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [Self.message(uid: sharedUID, id: targetId)],
        ])
        server.setUidValidity(1, for: "INBOX")
        server.expectMutation(rfc822MessageId: targetId)
        // E1 → E2 lands the instant the first `UID STORE 107` is acknowledged.
        // The decoy reuses the very same UID, which is exactly what a real
        // UIDVALIDITY reset is free to do.
        server.resetMailboxAfterNextSuccessfulResponse(
            containing: "UID STORE \(sharedUID)",
            mailbox: "INBOX",
            uidValidity: 2,
            messages: [Self.message(uid: sharedUID, id: decoyId)]
        )
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            // (1) Armed but not fired: an unrelated round-trip must not
            // trigger it.
            _ = try await client.noop()
            let beforeSelection = try await client.selectMailbox("INBOX")
            #expect(beforeSelection.uidValidity.value == 1)
            #expect(server.messageIDs(in: "INBOX") == ["<\(targetId)>"])

            // The E1 mutation: correct, and the oracle agrees.
            try await client.store(flags: [.seen], on: UIDSet(UID(sharedUID)), operation: .add)
            #expect(server.wrongMessageViolations().isEmpty)

            // (2) The epoch moved the moment that response was written.
            let afterSelection = try await client.selectMailbox("INBOX")
            #expect(afterSelection.uidValidity.value == 2)

            // (3) The same UID now denotes a different message entirely — the
            // E1 target is gone from the mailbox and the decoy holds its UID.
            #expect(server.messageIDs(in: "INBOX") == ["<\(decoyId)>"])
            #expect(server.flags(in: "INBOX", rfc822MessageId: targetId) == nil)
            // The epoch replacement carries flags too: the decoy starts clean
            // even though the pre-reset occupant of UID 107 had just been
            // marked \Seen.
            #expect(server.flags(in: "INBOX", uid: sharedUID).isEmpty)

            // The byte-identical repeat of the E1 command now mutates the decoy.
            try await client.store(flags: [.seen], on: UIDSet(UID(sharedUID)), operation: .add)
            #expect(server.flags(in: "INBOX", rfc822MessageId: decoyId)?.contains("\\Seen") == true)
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command.hasPrefix("UID STORE"))
        #expect(violations[0].uid == sharedUID)
        #expect(violations[0].actualRfc == decoyId)
        #expect(violations[0].expectedRfcs == [targetId])
    }

    /// The reset is one-shot and consumed on first match: a second occurrence
    /// of the same command does not re-apply it. A test that armed once must
    /// be able to keep driving the wire afterwards without the mailbox
    /// silently rewinding under it.
    ///
    /// Inversion evidence (recorded 2026-07-30): with the post-response reset
    /// application made unreachable, both UIDVALIDITY assertions fail
    /// (`3 == 4`); with only `recordOracleCheck` neutralized this test stays
    /// green, since it asserts nothing about the oracle.
    @Test("post-response reset is consumed by the first matching response only")
    func postResponseResetAppliesExactlyOnce() async throws {
        let targetId = "oracle-epoch-once-target@example.com"
        let decoyId = "oracle-epoch-once-decoy@example.com"
        let survivorId = "oracle-epoch-once-survivor@example.com"
        let sharedUID = 161
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [Self.message(uid: sharedUID, id: targetId)],
        ])
        server.setUidValidity(3, for: "INBOX")
        server.resetMailboxAfterNextSuccessfulResponse(
            containing: "UID STORE \(sharedUID)",
            mailbox: "INBOX",
            uidValidity: 4,
            messages: [Self.message(uid: sharedUID, id: decoyId)]
        )
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.store(flags: [.seen], on: UIDSet(UID(sharedUID)), operation: .add)
            let afterFirstStore = try await client.selectMailbox("INBOX")
            #expect(afterFirstStore.uidValidity.value == 4)

            // A message arriving after the reset must survive the second STORE.
            server.setMessages(
                [Self.message(uid: sharedUID, id: decoyId), Self.message(uid: 162, id: survivorId)],
                in: "INBOX"
            )
            try await client.store(flags: [.flagged], on: UIDSet(UID(sharedUID)), operation: .add)

            let afterSecondStore = try await client.selectMailbox("INBOX")
            #expect(afterSecondStore.uidValidity.value == 4)
        }

        #expect(Set(server.messageIDs(in: "INBOX")) == ["<\(decoyId)>", "<\(survivorId)>"])
    }

    // MARK: - The oracle sees real production traffic

    /// Closes the loop between the two halves above: the oracle is not a
    /// property of the raw-wire tests, it hooks whatever reaches the fake —
    /// including a mutation issued by the real `IMAPProvider`. `markRead`
    /// resolves its target by SEARCH and STOREs the resulting UID; the test
    /// declares a DIFFERENT message, so the STORE that lands is by
    /// construction a wrong-message mutation, and no future production change
    /// can make that declaration correct.
    @Test("oracle observes a UID STORE issued by the real IMAPProvider")
    func oracleObservesProductionIMAPProviderStore() async throws {
        let occupantId = "oracle-prod-occupant@example.com"
        let declaredId = "oracle-prod-declared@example.com"
        let occupantUID = 171
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: 172, id: declaredId),
            ],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        let provider = IMAPProvider(
            host: "127.0.0.1",
            port: server.port,
            username: server.username,
            password: server.password,
            smtpHost: "127.0.0.1",
            smtpPort: 587,
            useTLS: false
        )
        try await provider.connect()
        try await provider.markRead(ids: [occupantId], folder: "INBOX")
        try? await provider.disconnect()

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command.hasPrefix("UID STORE"))
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        #expect(server.flags(in: "INBOX", uid: occupantUID).contains("\\Seen"))
    }

    // MARK: - Deliverable 3: the sequence-set parser cannot narrow a mutation

    /// The oracle above resolves each UID that `parseUIDSet` hands the mutating
    /// handlers, so the SET those handlers receive is the oracle's substrate: a
    /// parser that returns fewer UIDs than the client addressed makes the fake
    /// mutate fewer messages than a real server would, and every
    /// `wrongMessageViolations().isEmpty` assertion downstream then certifies a
    /// narrower mutation than the one actually issued.
    ///
    /// THE INVARIANT: a `seq-range` denotes the same inclusive set regardless
    /// of endpoint order. RFC 3501 §9 states it verbatim — *"two seq-number
    /// values and all values between these two regardless of order. Example:
    /// 2:4 and 4:2 are equivalent and indicate values 2, 3, and 4."* — so a
    /// descending range is ordinary, protocol-legal input, NOT a malformed set
    /// to be rejected or truncated.
    ///
    /// THE OTHER TWO INVARIANTS, same substrate, same consequence: `*` is a
    /// BOUND (RFC 3501 §9 — "the largest number in use"), so discarding it
    /// narrows exactly as a descending-range guard would; and a MALFORMED
    /// component must address NOTHING, because dropping its unparseable token
    /// and re-reading the survivors turns narrowing into WIDENING — the fake
    /// then mutates a message the client never named, which is strictly worse.
    /// A syntactically valid full-UID-space range must also resolve without
    /// being materialised.
    ///
    /// Asserted at the parser HERE, and over the wire in
    /// `wireLevelUIDSetsMutateExactlyTheAddressedMessages` below — the latter
    /// is the one that pins the property that matters (what the fake actually
    /// mutates); this one enumerates the input space cheaply. Neither can be
    /// driven through SwiftMail, because the client cannot express any of these
    /// inputs. `MessageIdentifierSet` (SwiftMail's `UIDSet`)
    /// stores its members in a `private var indexSet: Foundation.IndexSet`, and
    /// EVERY initialiser — including the range ones and `init?(string:)` —
    /// writes through that one property. `IndexSet` keeps sorted, coalesced
    /// ranges, and the set renders via `indexSet.rangeView`, which yields those
    /// ranges in ascending order. So the emitted `sequence-set` is ascending no
    /// matter how the value was built; endpoint order is normalised away before
    /// anything reaches the wire.
    ///
    /// Its five range-taking initialisers reinforce this rather than carry it:
    /// three are closed (`ClosedRange<Int>`, the variadic `ranges:
    /// ClosedRange<Int>...`, and `ClosedRange<Identifier>`) and a `ClosedRange`
    /// traps on `5...2` rather than representing it, so a descending closed
    /// range cannot be formed at all; the other two (`PartialRangeFrom<Int>`,
    /// `PartialRangeFrom<Identifier>`) have no upper bound to invert and are
    /// normalised to `lowerBound...UInt32.max`. `init?(string:)` splits on `-`,
    /// not `:`, so it cannot even be handed `"5:2"`.
    ///
    /// SwiftMail therefore cannot emit a descending range — nor a `*` on any
    /// mutating path, nor a malformed set at all. Those sets come from OTHER
    /// clients and from fuzzed command streams, which is exactly the input
    /// class the fake must survive, so the sibling wire test hand-writes them
    /// through a purpose-built raw-socket client rather than a library.
    @Test("a descending UID range expands to the same inclusive set as its ascending twin")
    func descendingUIDRangeExpandsInclusivelyInBothDirections() {
        // UID 6 is deliberately ABSENT. Every expectation below is therefore
        // also an assertion that the parser INTERSECTS the mailbox rather than
        // enumerating a range: an implementation that materialised `min...max`
        // would invent a UID 6 that no message holds.
        let roster = [1, 2, 3, 4, 5, 7, 8, 9]

        let ascending = FakeIMAPServer.resolveUIDSet("2:5", againstMailboxUIDs: roster)
        let descending = FakeIMAPServer.resolveUIDSet("5:2", againstMailboxUIDs: roster)

        #expect(
            ascending == [2, 3, 4, 5],
            "an ascending range must expand inclusively: got \(ascending)"
        )
        #expect(
            descending == [2, 3, 4, 5],
            "RFC 3501 §9: 5:2 and 2:5 are the SAME four UIDs — a narrower result means the fake mutates fewer messages than the client addressed: got \(descending)"
        )
        #expect(
            ascending == descending,
            "endpoint order changed the addressed set — 5:2 resolved to \(descending) against 2:5's \(ascending)"
        )

        // Composition: a comma-joined set mixes directions and single UIDs, and
        // every member still resolves inclusively.
        #expect(FakeIMAPServer.resolveUIDSet("9:7,1,4:5", againstMailboxUIDs: roster) == [7, 8, 9, 1, 4, 5])

        // A single UID and a degenerate range are unchanged by the ordering.
        #expect(FakeIMAPServer.resolveUIDSet("3", againstMailboxUIDs: roster) == [3])
        #expect(FakeIMAPServer.resolveUIDSet("3:3", againstMailboxUIDs: roster) == [3])

        // A UID the mailbox does not hold is IGNORED (RFC 3501 §6.4.8), not
        // invented — the gap in the roster is the proof.
        #expect(FakeIMAPServer.resolveUIDSet("6", againstMailboxUIDs: roster) == [])
        #expect(FakeIMAPServer.resolveUIDSet("5:7", againstMailboxUIDs: roster) == [5, 7])

        // `*` IS A BOUND, NOT A TOKEN TO DROP. `*` is the mailbox's largest UID
        // (RFC 3501 §9), so an open-ended range reaches the end of the mailbox
        // in either direction, and a bare `*` names exactly the last message.
        #expect(
            FakeIMAPServer.resolveUIDSet("1:*", againstMailboxUIDs: roster) == roster,
            "1:* must address the whole mailbox — dropping `*` collapses it to the single UID 1"
        )
        #expect(
            FakeIMAPServer.resolveUIDSet("*:1", againstMailboxUIDs: roster) == roster,
            "*:1 is 1:* — order-independence applies to a resolved wildcard exactly as it does to a literal"
        )
        #expect(FakeIMAPServer.resolveUIDSet("*", againstMailboxUIDs: roster) == [9])
        #expect(FakeIMAPServer.resolveUIDSet("7:*", againstMailboxUIDs: roster) == [7, 8, 9])

        // A MALFORMED COMPONENT CONTRIBUTES NOTHING. The failure mode this
        // guards is not narrowing but WIDENING: dropping the unparseable token
        // from `1:x:3` leaves `1` and `3`, which read as a well-formed range
        // and expand to include UID 2 — a message the client never addressed.
        #expect(
            FakeIMAPServer.resolveUIDSet("1:x:3", againstMailboxUIDs: roster) == [],
            "a malformed component must address NOTHING — resolving it to a range mutates messages the client never named"
        )
        #expect(
            FakeIMAPServer.resolveUIDSet("1:2:3", againstMailboxUIDs: roster) == [],
            "three bounds is not a seq-range; keeping the first two silently rewrites the client's set"
        )
        #expect(FakeIMAPServer.resolveUIDSet(":", againstMailboxUIDs: roster) == [])
        #expect(FakeIMAPServer.resolveUIDSet("", againstMailboxUIDs: roster) == [])
        #expect(FakeIMAPServer.resolveUIDSet("1:", againstMailboxUIDs: roster) == [])
        #expect(FakeIMAPServer.resolveUIDSet(":5", againstMailboxUIDs: roster) == [])
        // …and it poisons only its own component, not its well-formed siblings.
        #expect(FakeIMAPServer.resolveUIDSet("1:x:3,4", againstMailboxUIDs: roster) == [4])

        // A SYNTACTICALLY VALID HUGE RANGE MUST NOT BE MATERIALISED. `1:2^32-1`
        // is legal input; `Array(1...4294967295)` is ~4 billion `Int`s. That the
        // call returns at all is the assertion — intersection is bounded by the
        // mailbox, not by the range's width.
        #expect(
            FakeIMAPServer.resolveUIDSet("1:4294967295", againstMailboxUIDs: roster) == roster,
            "a full-UID-space range must resolve to the mailbox's own UIDs, without enumerating the range"
        )

        // An empty mailbox addresses nothing, whatever the set says.
        #expect(FakeIMAPServer.resolveUIDSet("1:*", againstMailboxUIDs: []) == [])
        #expect(FakeIMAPServer.resolveUIDSet("2:5", againstMailboxUIDs: []) == [])
    }

    /// The same property at the SYSTEM level: what a real `UID STORE` /
    /// `UID COPY` on the wire actually mutates. The test above pins the helper's
    /// return value; this one pins the thing that matters — *the fake mutates
    /// exactly the messages the client addressed, no more and no fewer* — by
    /// speaking the two commands and then reading the resulting server state.
    ///
    /// Driven over a raw socket because **no client in this tree can express
    /// these inputs.** SwiftMail's `MessageIdentifierSet` normalises endpoint
    /// order away through a `Foundation.IndexSet`, has no way to spell a
    /// malformed set, and only reaches an unbounded `*` through the
    /// `PartialRangeFrom` initialisers its FETCH APIs use — none of which
    /// touches `UID STORE`/`UID COPY`. Since the input class the parser exists
    /// to survive is precisely "OTHER clients and fuzzed command streams", the
    /// test has to be one of those other clients.
    ///
    /// ⚑ NO REFERENCE — INVENTED. `v2final` has no `FakeIMAPServerOracleTests`
    /// at all and no raw-socket IMAP client anywhere in `TabMailTests/`
    /// (verified: `TabMailTests/Infrastructure/FakeIMAPServer.swift` is the only
    /// file in the tree that opens a socket, and it is the SERVER side). Both
    /// the client below and this case are new.
    @Test("a wildcard and a malformed UID set mutate exactly the addressed messages on the wire")
    func wireLevelUIDSetsMutateExactlyTheAddressedMessages() throws {
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: 11, id: "wire-set-first@example.com"),
                Self.message(uid: 12, id: "wire-set-second@example.com"),
                Self.message(uid: 13, id: "wire-set-third@example.com"),
            ],
            "Archive": [],
        ])
        try server.start()
        defer { server.stop() }

        let client = try RawIMAPClient(port: server.port)
        defer { client.close() }
        try client.readGreeting()
        _ = try client.command(tag: "a1", "LOGIN \(server.username) \(server.password)")
        _ = try client.command(tag: "a2", "SELECT INBOX")

        // 1. WILDCARD — `11:*` addresses every message from 11 to the end of the
        //    mailbox. Dropping `*` leaves the single bound 11, so only the first
        //    message would be flagged and the other two would silently escape a
        //    mutation the client did issue.
        _ = try client.command(tag: "a3", "UID STORE 11:* +FLAGS (\\Seen)")
        #expect(
            server.flags(in: "INBOX", uid: 11).contains("\\Seen"),
            "UID 11 was named by the range's lower bound and must be flagged"
        )
        #expect(
            server.flags(in: "INBOX", uid: 12).contains("\\Seen"),
            "UID 12 lies inside 11:* — an unresolved `*` narrowed the STORE to UID 11 alone"
        )
        #expect(
            server.flags(in: "INBOX", uid: 13).contains("\\Seen"),
            "UID 13 is the mailbox's `*` — an unresolved `*` narrowed the STORE to UID 11 alone"
        )

        // 2. MALFORMED — `11:x:13` is not a sequence-set. It must mutate
        //    NOTHING. Dropping the unparseable token leaves 11 and 13, which
        //    read as a range and would flag UID 12: a message the client never
        //    addressed, in a command it never validly issued.
        _ = try client.command(tag: "a4", "UID STORE 11:x:13 +FLAGS (\\Flagged)")
        for uid in [11, 12, 13] {
            #expect(
                !server.flags(in: "INBOX", uid: uid).contains("\\Flagged"),
                "a malformed UID set mutated UID \(uid) — the fake touched a message no valid command addressed"
            )
        }

        // 3. The same two properties on the COPY path, where a widened set
        //    duplicates real mail rather than merely restamping a flag.
        _ = try client.command(tag: "a5", "UID COPY 12:* \"Archive\"")
        #expect(
            Set(server.messageIDs(in: "Archive")) == [
                "<wire-set-second@example.com>", "<wire-set-third@example.com>",
            ],
            "UID COPY 12:* must copy exactly UIDs 12 and 13: got \(server.messageIDs(in: "Archive"))"
        )

        _ = try client.command(tag: "a6", "UID COPY 11:x:13 \"Archive\"")
        #expect(
            server.messageIDs(in: "Archive").count == 2,
            "a malformed UID COPY set copied messages — Archive holds \(server.messageIDs(in: "Archive"))"
        )

        // The source mailbox is untouched by COPY (RFC 3501 §6.4.7), so a
        // widened set cannot hide as a moved-away message either.
        #expect(server.messageIDs(in: "INBOX").count == 3)

        _ = try client.command(tag: "a7", "LOGOUT")
    }

    // MARK: - Deliverable 4: a bound that is not an `nz-number` addresses NOTHING

    /// `Int(_:)` is not a parser for RFC 3501's `nz-number`. It accepts a strictly
    /// larger language, and every extra form it admits WIDENS the resolved set —
    /// the same widening class the previous round claimed to close, surviving
    /// inside that round's own fix. Measured against the pre-fix parser:
    /// `Int("0") == 0`, `Int("-1") == -1`, `Int("+1") == 1`, `Int("007") == 7`,
    /// `Int("4294967296") == 4294967296`. So `0:2` and `-1:2` resolved to ranges
    /// whose floor sits BELOW the mailbox's first UID and swept in messages the
    /// client never named, and `1:4294967296` reached past the top of the 32-bit
    /// UID space.
    ///
    /// Why this is worse than ordinary widening: on every one of these inputs a
    /// CORRECT parser contributes nothing at all, so each UID the old parser
    /// resolved was a mutation with no legitimate counterpart — pure invention by
    /// the substrate the wrong-message oracle runs on.
    ///
    /// The grammar (RFC 3501 §9): `nz-number = digit-nz *DIGIT` — ASCII digits, no
    /// sign, no leading zero, non-zero — and §2.3.1.1 makes a UID 32-bit, so the
    /// accepted range is exactly `1 ... 4294967295`.
    ///
    /// ⚑ NO REFERENCE — INVENTED. `v2final:TabMailTests/Infrastructure/FakeIMAPServer.swift`'s
    /// `parseUIDSet(_ value: String) -> [Int]` uses a bare `Int(...)` on its bounds
    /// with no grammar check whatever, so the reference admits every form below.
    /// It simply never exercised them. There is nothing here to port.
    @Test("a bound that is not an nz-number addresses nothing — no sign, no zero, no leading zero, no overflow")
    func nonNZNumberBoundsAddressNothing() {
        // UID 6 absent, exactly as in the sibling test — a materialised range would
        // invent it.
        let roster = [1, 2, 3, 4, 5, 7, 8, 9]

        // ZERO is not an nz-number. `0:2` must not resolve; the old parser read it
        // as the range 0…2 and mutated UIDs 1 and 2.
        #expect(
            FakeIMAPServer.resolveUIDSet("0:2", againstMailboxUIDs: roster) == [],
            "0 is not an nz-number — 0:2 must address nothing, not the range 0…2"
        )
        #expect(FakeIMAPServer.resolveUIDSet("0", againstMailboxUIDs: roster) == [])

        // A SIGN is not part of the grammar. Both directions matter: `-1:2` widened
        // downward, `+1` was silently accepted as 1.
        #expect(
            FakeIMAPServer.resolveUIDSet("-1:2", againstMailboxUIDs: roster) == [],
            "-1 is not an nz-number — a negative floor sweeps in every UID below the range the client wrote"
        )
        #expect(FakeIMAPServer.resolveUIDSet("+1:2", againstMailboxUIDs: roster) == [])
        #expect(FakeIMAPServer.resolveUIDSet("-1", againstMailboxUIDs: roster) == [])
        #expect(FakeIMAPServer.resolveUIDSet("+3", againstMailboxUIDs: roster) == [])

        // A LEADING ZERO is not `digit-nz`. `007` must not silently become 7.
        #expect(
            FakeIMAPServer.resolveUIDSet("007", againstMailboxUIDs: roster) == [],
            "007 is not an nz-number — accepting it makes the parser answer a set the client could not have written"
        )
        #expect(FakeIMAPServer.resolveUIDSet("01:3", againstMailboxUIDs: roster) == [])

        // BEYOND 32 BITS. 4294967295 is the largest UID; 4294967296 is not one.
        #expect(
            FakeIMAPServer.resolveUIDSet("1:4294967296", againstMailboxUIDs: roster) == [],
            "a bound past the 32-bit UID space is not a UID — the component must contribute nothing"
        )
        #expect(FakeIMAPServer.resolveUIDSet("4294967296", againstMailboxUIDs: roster) == [])
        // ...while the largest LEGAL bound still resolves, so the cap is not off by one.
        #expect(
            FakeIMAPServer.resolveUIDSet("1:4294967295", againstMailboxUIDs: roster) == roster,
            "4294967295 IS a valid UID — rejecting it would narrow instead"
        )

        // WHITESPACE is not a digit. This is what the EXPUNGE call site used to hand
        // the parser when a client wrote two spaces after the verb.
        #expect(FakeIMAPServer.resolveUIDSet(" 1:3", againstMailboxUIDs: roster) == [])
        #expect(FakeIMAPServer.resolveUIDSet("1 : 3", againstMailboxUIDs: roster) == [])

        // A malformed bound poisons ONLY its own component, exactly as `1:x:3` does.
        #expect(FakeIMAPServer.resolveUIDSet("0:2,4", againstMailboxUIDs: roster) == [4])
        #expect(FakeIMAPServer.resolveUIDSet("4,-1:2", againstMailboxUIDs: roster) == [4])

        // And the well-formed cases are untouched by the new check.
        #expect(FakeIMAPServer.resolveUIDSet("2:5", againstMailboxUIDs: roster) == [2, 3, 4, 5])
        #expect(FakeIMAPServer.resolveUIDSet("1:*", againstMailboxUIDs: roster) == roster)
        #expect(FakeIMAPServer.resolveUIDSet("*", againstMailboxUIDs: roster) == [9])
    }

    /// The same property over the wire, on the two verbs that had NO wire-level pin
    /// at all — `UID MOVE` and `UID EXPUNGE`, which are precisely where a widened
    /// set LOSES mail rather than restamping a flag. The existing wire test drives
    /// only STORE and COPY.
    ///
    /// Driven raw for the same reason as its sibling: SwiftMail's
    /// `MessageIdentifierSet` cannot spell `0:2`, `-1:2` or `1:4294967296` at all,
    /// and the input class this parser exists to survive is other clients and
    /// fuzzed command streams.
    @Test("a non-nz-number UID set moves and expunges nothing on the wire")
    func wireLevelNonNZNumberSetsMoveAndExpungeNothing() throws {
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: 1, id: "wire-nz-first@example.com"),
                Self.message(uid: 2, id: "wire-nz-second@example.com"),
                Self.message(uid: 3, id: "wire-nz-third@example.com"),
            ],
            "Archive": [],
        ])
        try server.start()
        defer { server.stop() }

        let client = try RawIMAPClient(port: server.port)
        defer { client.close() }
        try client.readGreeting()
        _ = try client.command(tag: "b1", "LOGIN \(server.username) \(server.password)")
        _ = try client.command(tag: "b2", "SELECT INBOX")

        // 1. UID MOVE with a zero floor. The old parser read `0:2` as the range 0…2
        //    and would have MOVED UIDs 1 and 2 out of the mailbox — mail the client
        //    never addressed, gone from INBOX.
        _ = try client.command(tag: "b3", "UID MOVE 0:2 \"Archive\"")
        #expect(
            server.messageIDs(in: "Archive").isEmpty,
            "a zero-floored UID MOVE relocated mail: Archive holds \(server.messageIDs(in: "Archive"))"
        )
        #expect(
            server.messageIDs(in: "INBOX").count == 3,
            "INBOX lost messages to a set no valid command addressed: \(server.messageIDs(in: "INBOX"))"
        )

        // 2. UID MOVE with a negative floor — same shape, the other malformed sign.
        _ = try client.command(tag: "b4", "UID MOVE -1:2 \"Archive\"")
        #expect(server.messageIDs(in: "Archive").isEmpty)
        #expect(server.messageIDs(in: "INBOX").count == 3)

        // 3. UID EXPUNGE with an out-of-range bound. This is the destructive verb:
        //    a widened set here DELETES mail outright, with nothing to recover from.
        _ = try client.command(tag: "b5", "UID EXPUNGE 1:4294967296")
        #expect(
            server.messageIDs(in: "INBOX").count == 3,
            "an out-of-range UID EXPUNGE destroyed mail: INBOX holds \(server.messageIDs(in: "INBOX"))"
        )

        // 4. UID EXPUNGE with a leading-zero bound.
        _ = try client.command(tag: "b6", "UID EXPUNGE 001:2")
        #expect(server.messageIDs(in: "INBOX").count == 3)

        // 5. The verbs DO still work on a well-formed set — otherwise every
        //    expectation above would pass vacuously on a parser that rejects
        //    everything. `2:3` is legal and must move exactly those two.
        _ = try client.command(tag: "b7", "UID MOVE 2:3 \"Archive\"")
        #expect(
            Set(server.messageIDs(in: "Archive")) == [
                "<wire-nz-second@example.com>", "<wire-nz-third@example.com>",
            ],
            "a well-formed UID MOVE must still move exactly its set: got \(server.messageIDs(in: "Archive"))"
        )
        #expect(server.messageIDs(in: "INBOX") == ["<wire-nz-first@example.com>"])

        _ = try client.command(tag: "b8", "LOGOUT")
    }

    /// The EXPUNGE call site passes its arguments RAW — it is the one UID
    /// subcommand with no `split(maxSplits: 1)` to strip the separator, because it
    /// takes a sequence-set and nothing else. `resolveUIDSet` never splits on
    /// space, so an extra space used to reach the parser as part of the bound,
    /// which then failed the grammar and made the whole command a silent no-op
    /// answered `OK`. Narrowing rather than widening — but a command that reports
    /// success while doing nothing is exactly how a fake certifies a broken client
    /// as correct.
    @Test("UID EXPUNGE with extra whitespace still expunges the set it names")
    func wireLevelUIDExpungeToleratesExtraWhitespace() throws {
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: 1, id: "wire-ws-first@example.com"),
                Self.message(uid: 2, id: "wire-ws-second@example.com"),
                Self.message(uid: 3, id: "wire-ws-third@example.com"),
            ],
        ])
        try server.start()
        defer { server.stop() }

        let client = try RawIMAPClient(port: server.port)
        defer { client.close() }
        try client.readGreeting()
        _ = try client.command(tag: "c1", "LOGIN \(server.username) \(server.password)")
        _ = try client.command(tag: "c2", "SELECT INBOX")

        // Two spaces after the verb. Pre-trim this resolved to [] and answered OK.
        _ = try client.command(tag: "c3", "UID EXPUNGE  1:2")
        #expect(
            server.messageIDs(in: "INBOX") == ["<wire-ws-third@example.com>"],
            "UID EXPUNGE silently expunged nothing while answering OK: INBOX holds \(server.messageIDs(in: "INBOX"))"
        )

        _ = try client.command(tag: "c4", "LOGOUT")
    }
}

/// A minimal raw-socket IMAP client: enough to log in, select, and issue a
/// hand-written command line whose exact bytes the test controls. It exists so
/// a test can send a `sequence-set` no real client library in this tree can
/// construct (see `wireLevelUIDSetsMutateExactlyTheAddressedMessages`).
///
/// Blocking POSIX I/O against `127.0.0.1` with a receive timeout, so a fake
/// that stops answering fails the test with a thrown error instead of hanging
/// the suite.
///
/// ⚑ NO REFERENCE — INVENTED. `v2final` contains no raw-socket IMAP client;
/// its FakeIMAPServer tests all drive `SwiftMail.IMAPServer`.
private final class RawIMAPClient {
    enum Failure: Error {
        case socket(String)
        case io(String)
    }

    private let fd: Int32

    init(port: Int, timeoutSeconds: Int = 10) throws {
        fd = socket(AF_INET, SOCK_STREAM, 0)
        guard fd >= 0 else { throw Failure.socket("socket() failed: \(errno)") }

        var timeout = timeval(tv_sec: timeoutSeconds, tv_usec: 0)
        setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &timeout, socklen_t(MemoryLayout<timeval>.size))
        setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &timeout, socklen_t(MemoryLayout<timeval>.size))

        var addr = sockaddr_in()
        addr.sin_len = UInt8(MemoryLayout<sockaddr_in>.size)
        addr.sin_family = sa_family_t(AF_INET)
        addr.sin_port = UInt16(port).bigEndian
        addr.sin_addr.s_addr = inet_addr("127.0.0.1")
        let connected = withUnsafePointer(to: &addr) {
            $0.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                connect(fd, $0, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard connected == 0 else {
            Darwin.close(fd)
            throw Failure.socket("connect() failed: \(errno)")
        }
    }

    /// Consume the server's `* OK …` connection greeting.
    func readGreeting() throws {
        _ = try readUntil { $0.hasPrefix("* OK") }
    }

    /// Send `tag SPACE line CRLF` and read through the matching tagged response.
    @discardableResult
    func command(tag: String, _ line: String) throws -> String {
        try write("\(tag) \(line)\r\n")
        return try readUntil { $0.contains("\r\n\(tag) ") || $0.hasPrefix("\(tag) ") }
    }

    func close() {
        Darwin.close(fd)
    }

    private func write(_ text: String) throws {
        let bytes = Array(text.utf8)
        var sent = 0
        while sent < bytes.count {
            let written = bytes.withUnsafeBytes { buffer -> Int in
                Darwin.write(fd, buffer.baseAddress!.advanced(by: sent), bytes.count - sent)
            }
            guard written > 0 else { throw Failure.io("write() failed: \(errno)") }
            sent += written
        }
    }

    private func readUntil(_ isComplete: (String) -> Bool) throws -> String {
        var accumulated = ""
        var chunk = [UInt8](repeating: 0, count: 4096)
        while !isComplete(accumulated) {
            let received = chunk.withUnsafeMutableBytes { buffer -> Int in
                Darwin.read(fd, buffer.baseAddress, 4096)
            }
            guard received > 0 else {
                throw Failure.io("read() returned \(received) (errno \(errno)) after: \(accumulated)")
            }
            accumulated += String(decoding: chunk[0..<received], as: UTF8.self)
        }
        return accumulated
    }
}
