/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import Testing
import Foundation
import SwiftMail
@testable import TabMail

/// T0.2 — the red-first proof for the two `FakeIMAPServer` mechanisms the v3
/// safety work is built on. Both mechanisms landed with T0.1 (they are woven
/// through the fake's state and every mutating handler, so they could not be
/// excluded); what did NOT land is the evidence that they actually work.
///
/// **Deliverable 1 — the wrong-message wire oracle.** Every mutating IMAP
/// command (`UID STORE`, `UID MOVE`, `UID COPY`, `UID EXPUNGE`, plain
/// `EXPUNGE`) resolves its target UID to the mailbox's CURRENT occupant
/// in-lock, pre-mutation, and records a `WrongMessageViolation` when that
/// occupant's Message-ID is not one the test declared it was mutating. This is
/// the primary instrument for C3-I1…C3-I6 (`PLAN_IOS_REFACTOR_V3.md` §3.2):
/// every later Tier-2/Tier-3 test asserts `wrongMessageViolations().isEmpty`,
/// and an assertion that can never fail proves nothing. These tests are the
/// positive control for that assertion.
///
/// **Deliverable 2 — the epoch-replacement model.**
/// `resetMailboxAfterNextSuccessfulResponse` applies a complete mailbox epoch
/// replacement (UIDVALIDITY + message list + flags) immediately after the
/// matching command's successful response is written to the client. That is
/// what makes the mid-sequence epoch hazard reproducible at all: a UID
/// resolved under epoch E1 and mutated after the mailbox has moved to E2
/// lands on a different message. A later Tier-3 item uses exactly this to
/// prove the IMAP move path cannot mutate the wrong message.
///
/// **Why these drive the wire directly instead of a provider API.** These are
/// harness tests: they pin the FAKE's contract, so they must stay true no
/// matter how production changes. A test that produced the mis-target by
/// exploiting a production defect would go green the moment that defect is
/// fixed — an oracle proof that self-destructs. Here the mis-target comes from
/// the TEST's own declaration (it registers B and mutates A's UID), which no
/// production change can ever make correct. One test
/// (`oracleObservesProductionIMAPProviderStore`) closes the loop by proving
/// the oracle also sees traffic generated by the real `IMAPProvider`.
///
/// `.serialized` — the fake binds a listening socket; parallel tests would
/// contend on ephemeral port allocation.
@Suite("FakeIMAPServer wrong-message oracle + epoch-replacement model", .serialized)
struct FakeIMAPServerOracleTests {

    // MARK: - Fixtures

    private static func rfc822(messageId: String, subject: String = "oracle-fixture") -> String {
        """
        From: Test Sender <sender@example.com>\r
        To: Recipient <recipient@example.com>\r
        Subject: \(subject)\r
        Date: Thu, 01 Jan 2026 00:00:00 +0000\r
        Message-ID: <\(messageId)>\r
        Content-Type: text/plain; charset=utf-8\r
        \r
        oracle fixture body.\r

        """
    }

    private static func message(uid: Int, id: String) -> FakeIMAPServer.Message {
        FakeIMAPServer.makeMessage(uid: uid, rfc822Text: rfc822(messageId: id))
    }

    /// Runs `body` against a freshly logged-in raw SwiftMail client and logs
    /// out before returning. Driving the wire directly is deliberate — see the
    /// suite doc comment. The logout is awaited rather than deferred into a
    /// detached `Task`, so it can never race the fake's socket teardown.
    private static func withClient<T>(
        _ server: FakeIMAPServer,
        _ body: (SwiftMail.IMAPServer) async throws -> T
    ) async throws -> T {
        let client = SwiftMail.IMAPServer(host: "127.0.0.1", port: server.port, useTLS: false)
        try await client.connect()
        try await client.login(username: server.username, password: server.password)
        do {
            let result = try await body(client)
            try? await client.logout()
            return result
        } catch {
            try? await client.logout()
            throw error
        }
    }

    // MARK: - Deliverable 1: the oracle fires

    /// THE headline red-first proof for T0.2: a `UID STORE` aimed at a UID
    /// whose current occupant is not the message the test declared it was
    /// mutating raises exactly one `WrongMessageViolation`, naming the
    /// command, the mailbox, the UID, and the Message-ID that was actually
    /// hit.
    ///
    /// Inversion evidence (recorded 2026-07-30): with `recordOracleCheck`'s
    /// body neutralized to an immediate `return`, this test fails at the
    /// `violations.count == 1` expectation — it goes green-when-it-should-be-
    /// red. It passes only because the oracle exists.
    @Test("oracle fires on a UID STORE aimed at a UID the test never declared")
    func oracleFiresOnMisTargetedUIDStore() async throws {
        let occupantId = "oracle-store-occupant@example.com"
        let declaredId = "oracle-store-declared@example.com"
        let occupantUID = 101
        let declaredUID = 102
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: declaredUID, id: declaredId),
            ],
        ])
        // The test declares it is mutating `declaredId` — and then deliberately
        // mis-targets UID 101, whose current occupant is `occupantId`.
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.store(flags: [.seen], on: UIDSet(UID(occupantUID)), operation: .add)
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command.hasPrefix("UID STORE"))
        #expect(violations[0].mailbox == "INBOX")
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        #expect(violations[0].expectedRfcs == [declaredId])
        // The oracle OBSERVES; it never blocks. The wrong-message mutation
        // really did land — which is precisely the class of defect it exists
        // to make visible.
        #expect(server.flags(in: "INBOX", uid: occupantUID).contains("\\Seen"))
    }

    /// The negative control for the test above: the same STORE, aimed at the
    /// UID the test DID declare, records nothing. Without this, a
    /// permanently-firing oracle would also satisfy the positive proof.
    @Test("oracle stays silent on a correctly targeted UID STORE")
    func oracleStaysSilentOnCorrectlyTargetedUIDStore() async throws {
        let declaredId = "oracle-store-correct@example.com"
        let declaredUID = 103
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [Self.message(uid: declaredUID, id: declaredId)],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.store(flags: [.seen], on: UIDSet(UID(declaredUID)), operation: .add)
        }

        #expect(server.wrongMessageViolations().isEmpty)
        #expect(server.flags(in: "INBOX", uid: declaredUID).contains("\\Seen"))
    }

    /// The oracle is OPT-IN. While no expectation has ever been registered,
    /// every mutating handler's check is a single `isEmpty` branch — this is
    /// what keeps the other ~7,700 tests behaviorally unchanged. Exercises the
    /// whole mutating surface with no registration at all.
    @Test("oracle is inert until a test registers an expectation")
    func oracleIsInertWhenNoExpectationRegistered() async throws {
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: 111, id: "oracle-inert-a@example.com"),
                Self.message(uid: 112, id: "oracle-inert-b@example.com"),
                Self.message(uid: 113, id: "oracle-inert-c@example.com"),
                Self.message(uid: 114, id: "oracle-inert-d@example.com"),
            ],
            "Archive": [],
        ])
        server.setFlags(["\\Deleted"], in: "INBOX", uid: 114)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.store(flags: [.flagged], on: UIDSet(UID(111)), operation: .add)
            try await client.copy(messages: UIDSet(UID(111)), to: "Archive")
            try await client.move(messages: UIDSet(UID(112)), to: "Archive")
            try await client.expunge(messages: UIDSet(UID(113)))
            try await client.expunge()
        }

        // Every mutating command ran, and the oracle recorded nothing.
        let commands = server.recordedCommands()
        #expect(commands.contains { $0.hasPrefix("UID STORE") })
        #expect(commands.contains { $0.hasPrefix("UID COPY") })
        #expect(commands.contains { $0.hasPrefix("UID MOVE") })
        #expect(commands.contains { $0.hasPrefix("UID EXPUNGE") })
        #expect(commands.contains("EXPUNGE"))
        #expect(server.wrongMessageViolations().isEmpty)
    }

    @Test("oracle fires on a mis-targeted UID MOVE")
    func oracleFiresOnMisTargetedUIDMove() async throws {
        let occupantId = "oracle-move-occupant@example.com"
        let declaredId = "oracle-move-declared@example.com"
        let occupantUID = 121
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: 122, id: declaredId),
            ],
            "Archive": [],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            // Default capabilities advertise MOVE + UIDPLUS, so SwiftMail
            // issues an atomic `UID MOVE` rather than the COPY/STORE/EXPUNGE
            // fallback.
            try await client.move(messages: UIDSet(UID(occupantUID)), to: "Archive")
        }

        #expect(server.recordedCommands().contains { $0.hasPrefix("UID MOVE") })
        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command == "UID MOVE")
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        #expect(server.messageIDs(in: "Archive") == ["<\(occupantId)>"])
    }

    @Test("oracle fires on a mis-targeted UID COPY")
    func oracleFiresOnMisTargetedUIDCopy() async throws {
        let occupantId = "oracle-copy-occupant@example.com"
        let declaredId = "oracle-copy-declared@example.com"
        let occupantUID = 131
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: 132, id: declaredId),
            ],
            "Archive": [],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.copy(messages: UIDSet(UID(occupantUID)), to: "Archive")
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command == "UID COPY")
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        // COPY leaves the source in place (RFC 3501 §6.4.7) — the wrong
        // message was duplicated, not moved.
        #expect(server.messageIDs(in: "INBOX").contains("<\(occupantId)>"))
        #expect(server.messageIDs(in: "Archive") == ["<\(occupantId)>"])
    }

    @Test("oracle fires on a mis-targeted UID EXPUNGE")
    func oracleFiresOnMisTargetedUIDExpunge() async throws {
        let occupantId = "oracle-uidexpunge-occupant@example.com"
        let declaredId = "oracle-uidexpunge-declared@example.com"
        let occupantUID = 141
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: 142, id: declaredId),
            ],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.expunge(messages: UIDSet(UID(occupantUID)))
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command == "UID EXPUNGE")
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        #expect(server.messageIDs(in: "INBOX") == ["<\(declaredId)>"])
    }

    /// Plain `EXPUNGE` is mailbox-WIDE (RFC 3501 §6.4.3) — it names no UID at
    /// all, so it is the one mutating command whose blast radius the caller
    /// cannot see. C3-I5 forbids it on every action path for exactly this
    /// reason; the oracle resolves the \Deleted set the server is about to
    /// destroy and reports every member the test never declared.
    @Test("oracle fires on a plain EXPUNGE that destroys an undeclared Deleted message")
    func oracleFiresOnMisTargetedPlainExpunge() async throws {
        let bystanderId = "oracle-expunge-bystander@example.com"
        let declaredId = "oracle-expunge-declared@example.com"
        let bystanderUID = 151
        let declaredUID = 152
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: bystanderUID, id: bystanderId),
                Self.message(uid: declaredUID, id: declaredId),
            ],
        ])
        // A pre-existing \Deleted bystander the test never gestured on, plus
        // the declared target — a mailbox-wide EXPUNGE takes both.
        server.setFlags(["\\Deleted"], in: "INBOX", uid: bystanderUID)
        server.setFlags(["\\Deleted"], in: "INBOX", uid: declaredUID)
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.expunge()
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command == "EXPUNGE")
        #expect(violations[0].uid == bystanderUID)
        #expect(violations[0].actualRfc == bystanderId)
        // Both really are gone — the declared one legitimately, the bystander
        // as collateral. Only the bystander is reported.
        #expect(server.messageIDs(in: "INBOX").isEmpty)
    }

    // MARK: - Deliverable 2: the epoch-replacement model

    /// `resetMailboxAfterNextSuccessfulResponse` models a UIDVALIDITY change
    /// taking effect at an await boundary — immediately after a successful
    /// protocol response, without pausing either side of the socket. This test
    /// proves all three properties the later Tier-3 move-path proof depends on:
    ///
    /// 1. **Not eager.** After arming, and after an unrelated command has come
    ///    and gone, a SELECT still reports the OLD epoch.
    /// 2. **UIDVALIDITY really changes at that point.** The first SELECT after
    ///    the armed command reports the NEW epoch.
    /// 3. **The UID's referent really changes.** UID 107 denoted message A
    ///    before the reset and a different message afterwards — demonstrated
    ///    by re-issuing the IDENTICAL `UID STORE 107` and watching it land on
    ///    the decoy while the oracle reports the wrong-message hit.
    ///
    /// Property 3 IS the mid-sequence epoch hazard, reproduced end-to-end at
    /// the wire: the two STOREs are byte-identical commands, one correct and
    /// one catastrophic, and only the epoch between them differs.
    ///
    /// Inversion evidence (recorded 2026-07-30), run in both directions
    /// because the two mechanisms must be shown to be separable:
    /// - With `recordOracleCheck` neutralized, the epoch assertions (1 → 2)
    ///   and the decoy-flag assertion still hold — the epoch model is proven
    ///   independently of the oracle — while only the violation assertion
    ///   fails.
    /// - With the post-response reset application neutralized (the
    ///   `postResponseMailboxResets` block in the client loop made
    ///   unreachable), this test fails at the UIDVALIDITY assertion
    ///   (`1 == 2`), at the occupant assertion (INBOX still holds the E1
    ///   target), and at the violation assertion — while every oracle test
    ///   above stays green.
    @Test("post-response reset changes UIDVALIDITY and repoints the UID at a different message")
    func postResponseResetChangesUidValidityAndUidOccupant() async throws {
        let targetId = "oracle-epoch-target@example.com"
        let decoyId = "oracle-epoch-decoy@example.com"
        let sharedUID = 107
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [Self.message(uid: sharedUID, id: targetId)],
        ])
        server.setUidValidity(1, for: "INBOX")
        server.expectMutation(rfc822MessageId: targetId)
        // E1 → E2 lands the instant the first `UID STORE 107` is acknowledged.
        // The decoy reuses the very same UID, which is exactly what a real
        // UIDVALIDITY reset is free to do.
        server.resetMailboxAfterNextSuccessfulResponse(
            containing: "UID STORE \(sharedUID)",
            mailbox: "INBOX",
            uidValidity: 2,
            messages: [Self.message(uid: sharedUID, id: decoyId)]
        )
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            // (1) Armed but not fired: an unrelated round-trip must not
            // trigger it.
            _ = try await client.noop()
            let beforeSelection = try await client.selectMailbox("INBOX")
            #expect(beforeSelection.uidValidity.value == 1)
            #expect(server.messageIDs(in: "INBOX") == ["<\(targetId)>"])

            // The E1 mutation: correct, and the oracle agrees.
            try await client.store(flags: [.seen], on: UIDSet(UID(sharedUID)), operation: .add)
            #expect(server.wrongMessageViolations().isEmpty)

            // (2) The epoch moved the moment that response was written.
            let afterSelection = try await client.selectMailbox("INBOX")
            #expect(afterSelection.uidValidity.value == 2)

            // (3) The same UID now denotes a different message entirely — the
            // E1 target is gone from the mailbox and the decoy holds its UID.
            #expect(server.messageIDs(in: "INBOX") == ["<\(decoyId)>"])
            #expect(server.flags(in: "INBOX", rfc822MessageId: targetId) == nil)
            // The epoch replacement carries flags too: the decoy starts clean
            // even though the pre-reset occupant of UID 107 had just been
            // marked \Seen.
            #expect(server.flags(in: "INBOX", uid: sharedUID).isEmpty)

            // The byte-identical repeat of the E1 command now mutates the decoy.
            try await client.store(flags: [.seen], on: UIDSet(UID(sharedUID)), operation: .add)
            #expect(server.flags(in: "INBOX", rfc822MessageId: decoyId)?.contains("\\Seen") == true)
        }

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command.hasPrefix("UID STORE"))
        #expect(violations[0].uid == sharedUID)
        #expect(violations[0].actualRfc == decoyId)
        #expect(violations[0].expectedRfcs == [targetId])
    }

    /// The reset is one-shot and consumed on first match: a second occurrence
    /// of the same command does not re-apply it. A test that armed once must
    /// be able to keep driving the wire afterwards without the mailbox
    /// silently rewinding under it.
    ///
    /// Inversion evidence (recorded 2026-07-30): with the post-response reset
    /// application made unreachable, both UIDVALIDITY assertions fail
    /// (`3 == 4`); with only `recordOracleCheck` neutralized this test stays
    /// green, since it asserts nothing about the oracle.
    @Test("post-response reset is consumed by the first matching response only")
    func postResponseResetAppliesExactlyOnce() async throws {
        let targetId = "oracle-epoch-once-target@example.com"
        let decoyId = "oracle-epoch-once-decoy@example.com"
        let survivorId = "oracle-epoch-once-survivor@example.com"
        let sharedUID = 161
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [Self.message(uid: sharedUID, id: targetId)],
        ])
        server.setUidValidity(3, for: "INBOX")
        server.resetMailboxAfterNextSuccessfulResponse(
            containing: "UID STORE \(sharedUID)",
            mailbox: "INBOX",
            uidValidity: 4,
            messages: [Self.message(uid: sharedUID, id: decoyId)]
        )
        try server.start()
        defer { server.stop() }

        try await Self.withClient(server) { client in
            _ = try await client.selectMailbox("INBOX")
            try await client.store(flags: [.seen], on: UIDSet(UID(sharedUID)), operation: .add)
            let afterFirstStore = try await client.selectMailbox("INBOX")
            #expect(afterFirstStore.uidValidity.value == 4)

            // A message arriving after the reset must survive the second STORE.
            server.setMessages(
                [Self.message(uid: sharedUID, id: decoyId), Self.message(uid: 162, id: survivorId)],
                in: "INBOX"
            )
            try await client.store(flags: [.flagged], on: UIDSet(UID(sharedUID)), operation: .add)

            let afterSecondStore = try await client.selectMailbox("INBOX")
            #expect(afterSecondStore.uidValidity.value == 4)
        }

        #expect(Set(server.messageIDs(in: "INBOX")) == ["<\(decoyId)>", "<\(survivorId)>"])
    }

    // MARK: - The oracle sees real production traffic

    /// Closes the loop between the two halves above: the oracle is not a
    /// property of the raw-wire tests, it hooks whatever reaches the fake —
    /// including a mutation issued by the real `IMAPProvider`. `markRead`
    /// resolves its target by SEARCH and STOREs the resulting UID; the test
    /// declares a DIFFERENT message, so the STORE that lands is by
    /// construction a wrong-message mutation, and no future production change
    /// can make that declaration correct.
    @Test("oracle observes a UID STORE issued by the real IMAPProvider")
    func oracleObservesProductionIMAPProviderStore() async throws {
        let occupantId = "oracle-prod-occupant@example.com"
        let declaredId = "oracle-prod-declared@example.com"
        let occupantUID = 171
        let server = FakeIMAPServer(mailboxes: [
            "INBOX": [
                Self.message(uid: occupantUID, id: occupantId),
                Self.message(uid: 172, id: declaredId),
            ],
        ])
        server.expectMutation(rfc822MessageId: declaredId)
        try server.start()
        defer { server.stop() }

        let provider = IMAPProvider(
            host: "127.0.0.1",
            port: server.port,
            username: server.username,
            password: server.password,
            smtpHost: "127.0.0.1",
            smtpPort: 587,
            useTLS: false
        )
        try await provider.connect()
        try await provider.markRead(ids: [occupantId], folder: "INBOX")
        try? await provider.disconnect()

        let violations = server.wrongMessageViolations()
        #expect(violations.count == 1)
        guard violations.count == 1 else { return }
        #expect(violations[0].command.hasPrefix("UID STORE"))
        #expect(violations[0].uid == occupantUID)
        #expect(violations[0].actualRfc == occupantId)
        #expect(server.flags(in: "INBOX", uid: occupantUID).contains("\\Seen"))
    }
}
