/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

import SwiftUI

struct RemindersSettingsView: View {
    @State private var reminders: [Reminder] = []
    @State private var isLoading = true

    private var kbReminders: [Reminder] { reminders.filter { $0.source == "kb" } }
    private var emailReminders: [Reminder] { reminders.filter { $0.source == "message" } }
    private var displayedReminders: [Reminder] { reminders }

    var body: some View {
        Form {
            Group {
                // Explanation header
                Section {
                    Text("Reminders are generated by AI from your emails and knowledge base entries. Toggle to show or hide them. Knowledge base reminders can be permanently deleted by swiping left.")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }

                if isLoading {
                    Section {
                        HStack {
                            Spacer()
                            ProgressView()
                            Spacer()
                        }
                        .padding(.vertical, 20)
                    }
                } else if displayedReminders.isEmpty {
                    Section {
                        HStack {
                            Spacer()
                            Text("No active reminders")
                                .font(.subheadline)
                                .italic()
                                .foregroundStyle(.secondary)
                            Spacer()
                        }
                        .padding(.vertical, 20)
                    }
                } else {
                    // KB reminders section
                    if !kbReminders.isEmpty {
                        Section("Knowledge Base") {
                            ForEach(kbReminders, id: \.hash) { reminder in
                                if let index = reminders.firstIndex(where: { $0.hash == reminder.hash }) {
                                    ReminderRow(reminder: reminder) { enabled in
                                        toggleReminder(at: index, enabled: enabled)
                                    }
                                    .swipeActions(edge: .trailing, allowsFullSwipe: false) {
                                        Button(role: .destructive) {
                                            deleteKBReminder(at: index)
                                        } label: {
                                            Label("Delete", systemImage: "trash")
                                        }
                                    }
                                    .reportConcern(contentType: .chatMessage, content: reminder.content)
                                }
                            }
                        }
                    }

                    // Email reminders section
                    if !emailReminders.isEmpty {
                        Section("Email") {
                            ForEach(emailReminders, id: \.hash) { reminder in
                                if let index = reminders.firstIndex(where: { $0.hash == reminder.hash }) {
                                    ReminderRow(reminder: reminder) { enabled in
                                        toggleReminder(at: index, enabled: enabled)
                                    }
                                    .reportConcern(contentType: .chatMessage, content: reminder.content)
                                }
                            }
                        }
                    }
                }
            }
            .listRowBackground(Palette.boxBg)
        }
        .scrollContentBackground(.hidden)
        .background(Palette.previewPaneBg)
        .navigationTitle("Reminders")
        .navigationBarTitleDisplayMode(.inline)
        .refreshable { await loadReminders() }
        .task { await loadReminders() }
    }

    private func loadReminders() async {
        reminders = await ReminderBuilder.buildReminderList(includeDisabled: true)
        isLoading = false
    }

    private func toggleReminder(at index: Int, enabled: Bool) {
        let reminder = reminders[index]
        DisabledRemindersStore.setEnabled(hash: reminder.hash, enabled: enabled)
        reminders[index] = Reminder(
            type: reminder.type,
            content: reminder.content,
            dueDate: reminder.dueDate,
            dueTime: reminder.dueTime,
            source: reminder.source,
            hash: reminder.hash,
            enabled: enabled,
            action: reminder.action,
            messageId: reminder.messageId,
            uniqueId: reminder.uniqueId,
            subject: reminder.subject,
            from: reminder.from,
            instruction: reminder.instruction,
            scheduleDays: reminder.scheduleDays,
            scheduleDate: reminder.scheduleDate,
            scheduleTime: reminder.scheduleTime,
            timezone: reminder.timezone,
            rawLine: reminder.rawLine
        )
    }

    /// Permanently delete a KB reminder by applying a DEL patch to the knowledge base text.
    /// Same approach as `ReminderDelTool`: find the matching KB line, build a DEL patch, apply via KBPatchApplier.
    private func deleteKBReminder(at index: Int) {
        let reminder = reminders[index]
        guard reminder.source == "kb" else { return }

        let current = PromptStore.shared.kbText()
        let lines = current.components(separatedBy: "\n")
        let reminderPattern = /^-\s*(?:Reminder:|\[Reminder\])/.ignoresCase()

        // Find the KB line whose content matches this reminder
        let contentLower = reminder.content.lowercased()
        var matchedStatement: String?
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard trimmed.prefixMatch(of: reminderPattern) != nil else { continue }
            if trimmed.lowercased().contains(contentLower) {
                // Extract statement without leading "- "
                matchedStatement = trimmed.replacingOccurrences(of: "^-\\s*", with: "", options: .regularExpression)
                break
            }
        }

        guard let statement = matchedStatement else {
            print("[RemindersSettings] KB line not found for reminder: \(reminder.content.prefix(80))")
            reminders.remove(at: index)
            return
        }

        let patchText = "DEL\n\(statement)"
        guard let updated = KBPatchApplier.applyKBPatch(content: current, patchText: patchText),
              updated != current else {
            print("[RemindersSettings] KBPatchApplier DEL failed for: \(statement.prefix(80))")
            return
        }

        PromptStore.shared.rawKB = updated
        reminders.remove(at: index)
        print("[RemindersSettings] Deleted KB reminder: \(statement.prefix(80))")
    }

}

// MARK: - Reminder Row

private struct ReminderRow: View {
    let reminder: Reminder
    let onToggle: (Bool) -> Void

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Toggle("", isOn: Binding(
                get: { reminder.enabled },
                set: { onToggle($0) }
            ))
            .labelsHidden()
            .toggleStyle(.switch)
            .controlSize(.small)

            VStack(alignment: .leading, spacing: 4) {
                Text(reminder.content)
                    .font(.subheadline)

                if let due = dueDateLabel(for: reminder) {
                    Text(due.text)
                        .font(.caption2)
                        .foregroundStyle(due.urgency.color)
                        .fontWeight(due.urgency.weight)
                }

                // Email details line — tappable to open message
                if reminder.source == "message", let subject = reminder.subject, !subject.isEmpty,
                   let messageId = reminder.messageId, !messageId.isEmpty {
                    NavigationLink {
                        MessageDetailView(messageId: messageId)
                    } label: {
                        HStack(spacing: 4) {
                            Image(systemName: "envelope")
                                .font(.caption2)
                            Text(subject)
                                .font(.caption2)
                                .lineLimit(1)
                        }
                        .foregroundStyle(Palette.accentColor)
                    }
                    .buttonStyle(.plain)
                }
            }
        }
        .opacity(reminder.enabled ? 1.0 : 0.5)
        .animation(.easeInOut(duration: 0.2), value: reminder.enabled)
    }
}

// MARK: - Due Date Formatting

private enum DueDateUrgency {
    case overdue
    case today
    case tomorrow
    case future

    var color: Color {
        switch self {
        case .overdue: Palette.delete
        case .today, .tomorrow: Palette.archive
        case .future: .secondary
        }
    }

    var weight: Font.Weight {
        switch self {
        case .overdue: .semibold
        case .today, .tomorrow: .medium
        case .future: .regular
        }
    }
}

private func dueDateLabel(for reminder: Reminder) -> (text: String, urgency: DueDateUrgency)? {
    guard let dueDateStr = reminder.dueDate else { return nil }

    let parts = dueDateStr.split(separator: "-")
    guard parts.count == 3,
          let year = Int(parts[0]),
          let month = Int(parts[1]),
          let day = Int(parts[2]) else {
        return nil
    }

    let calendar = Calendar.current
    var comps = DateComponents()
    comps.year = year
    comps.month = month
    comps.day = day
    guard let dueDate = calendar.date(from: comps) else { return nil }

    let dueMidnight = calendar.startOfDay(for: dueDate)
    let todayMidnight = calendar.startOfDay(for: Date())
    guard let tomorrowMidnight = calendar.date(byAdding: .day, value: 1, to: todayMidnight) else {
        return nil
    }

    if dueMidnight < todayMidnight {
        let daysOverdue = calendar.dateComponents([.day], from: dueMidnight, to: todayMidnight).day ?? 0
        let dayWord = daysOverdue == 1 ? "day" : "days"
        return ("Overdue (\(daysOverdue) \(dayWord))", .overdue)
    } else if dueMidnight == todayMidnight {
        return ("Due Today", .today)
    } else if dueMidnight == tomorrowMidnight {
        return ("Due Tomorrow", .tomorrow)
    } else {
        let formatter = DateFormatter()
        formatter.dateFormat = "EEE, MMM d"
        return ("Due \(formatter.string(from: dueMidnight))", .future)
    }
}
